import type { Metadata } from "next"
import { Merriweather } from "next/font/google"
import "./globals.css"

// Configure the Merriweather font and expose it as a CSS variable.
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
})

// Standard Next.js metadata used by the app router.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Root layout that wraps every page.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.variable} font-serif antialiased`}>
        {children}
      </body>
    </html>
  )
}
